Traceback (most recent call last):
  File "main.py", line 236, in <module>
    val_metric_results = algorithm.evaluate(loader, cache = validation_cache[index])
  File "/data/healthy-ml/scratch/olawale/my-icrm/algorithms.py", line 687, in evaluate
    result = self._evaluate_robust(self.network, loader, self.hparams['metrics'],  cache)
  File "/data/healthy-ml/scratch/olawale/my-icrm/algorithms.py", line 525, in _evaluate_robust
    for batch_idx, (x, y) in enumerate(loader):
  File "/data/healthy-ml/scratch/olawale/my-icrm/utils.py", line 208, in __iter__
    yield next(self._infinite_iterator)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1327, in _next_data
    idx, data = self._get_data()
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1293, in _get_data
    success, data = self._try_get_data()
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1131, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/data/healthy-ml/scratch/olawale/anaconda3/envs/icrm/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 127, in tabulate
    import tabulate
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 934, in get_code
  File "<frozen importlib._bootstrap_external>", line 1033, in get_data
KeyboardInterrupt
